Feat: Adding solution for multiple chapters
RectangleHelpSchool/crypto-course-organy pull request #1
Opened 2024-03-05 15:44 UTC by organic1337

2024-03-05 16:11 UTC, danlaav1 requested changes

2024-03-05 16:11 UTC, danlaav1 commented on 03_data_dawg/python_exercise/my_approvals.py
> +    def _align_eoa(eoa: str) -> str:
check if it will work with address that start with zeros

2024-03-05 16:11 UTC, danlaav1 commented on 03_data_dawg/python_exercise/my_approvals.py
> +    main()
run pylint black formatter and mypy on the code make sure no warnings.

2024-03-05 16:11 UTC, danlaav1 commented on 03_data_dawg/python_exercise/my_approvals.py
> +    def _get_transaction(self, eoa: Address) -> None:
you are not using this function

2024-03-05 16:11 UTC, danlaav1 commented on 03_data_dawg/python_exercise/my_approvals.py
> +APPROVAL_SIGNATURE = '0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925'
Web3.sha3(text='Approval(address,address,uint256)').hex()

2024-03-05 16:11 UTC, danlaav1 commented on 03_data_dawg/python_exercise/my_approvals.py
> +        raw_approvals = [approval for approval in raw_approvals if
cool nice trick!

2024-03-05 16:11 UTC, danlaav1 commented on 03_data_dawg/python_exercise/my_approvals.py
> +        raw_approvals = self.w3.eth.get_logs({
try it on very early addresses I think it will failed but i am not sure testit on vitalik.eth

2024-03-05 16:16 UTC, organic1337 commented on 03_data_dawg/python_exercise/my_approvals.py
> +        abi = [{"inputs": [], "name": "name", "outputs": [{"internalType": "string", "name": "", "type": "string"}],
DONE1

2024-03-05 16:30 UTC, organic1337 commented on 03_data_dawg/python_exercise/my_approvals.py
> +    def _align_eoa(eoa: str) -> str:
I've looked for a function in web3 that implements and I coudn't find one even in their official documentation.
the JS library has `web3.utils.padLeft` but for some reason it is not present in python's version of the library.

2024-03-05 16:31 UTC, danlaav1 commented on 03_data_dawg/python_exercise/my_approvals.py
> +    def _align_eoa(eoa: str) -> str:
ok

2024-03-05 16:31 UTC, danlaav1 commented on 03_data_dawg/python_exercise/my_approvals.py
> +    def _align_eoa(eoa: str) -> str:
today we do it like that 
def zfill_address64(address: str) -> str:
    return "0x{:064x}".format(int(address.lower(), 16))

2024-03-05 16:39 UTC, organic1337 commented on 03_data_dawg/python_exercise/my_approvals.py
> +APPROVAL_SIGNATURE = '0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925'
```
(python_exercise) organic@Ors-MacBook-Pro: python_exercise [chapter9]× » pylint my_approvals.py                                                                                                                       28 [18:31:32]
************* Module my_approvals
my_approvals.py:11:0: C0301: Line too long (105/100) (line-too-long)
my_approvals.py:13:0: C0301: Line too long (107/100) (line-too-long)
my_approvals.py:1:0: C0114: Missing module docstring (missing-module-docstring)
my_approvals.py:19:0: C0115: Missing class docstring (missing-class-docstring)
my_approvals.py:24:0: C0116: Missing function or method docstring (missing-function-docstring)
my_approvals.py:30:0: C0115: Missing class docstring (missing-class-docstring)
my_approvals.py:44:4: C0116: Missing function or method docstring (missing-function-docstring)
my_approvals.py:30:0: R0903: Too few public methods (1/2) (too-few-public-methods)
my_approvals.py:68:0: C0116: Missing function or method docstring (missing-function-docstring)
```

These are the warnings I get. I ignored all of them because:
1) Not every scope should contain docstring
2) 100 characters in each line is very specific, I don't know what's the actual limit that our team defines in the pylint configuration so I will ignore it for now. BTW can you reference the pylint configuration so I will take a look?

2024-03-05 16:39 UTC, organic1337 commented on 03_data_dawg/python_exercise/my_approvals.py
> +        raw_approvals = [approval for approval in raw_approvals if
THX

2024-03-05 16:42 UTC, organic1337 commented on 03_data_dawg/python_exercise/my_approvals.py
> +APPROVAL_SIGNATURE = '0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925'
Mypy threw the following error:
```
my_approvals.py:42: error: No overload variant of "contract" of "Eth" matches argument types "str", "list[dict[str, Sequence[Collection[str]]]]"  [call-overload]
my_approvals.py:42: note: Possible overload variants:
my_approvals.py:42: note:     def contract(self, address: None = ..., **kwargs: Any) -> type[Contract]
my_approvals.py:42: note:     def contract(self, address: Address | ChecksumAddress | ENS, **kwargs: Any) -> Contract
my_approvals.py:49: error: List item 0 has incompatible type "str"; expected "Hash32 | HexBytes | HexStr | Sequence[Hash32 | HexBytes | HexStr] | None"  [list-item]
my_approvals.py:50: error: List item 1 has incompatible type "str"; expected "Hash32 | HexBytes | HexStr | Sequence[Hash32 | HexBytes | HexStr] | None"  [list-item]
Found 3 errors in 1 file (checked 1 source file)
```

that's because the web3 library type annotations has some bugs.
I've fixed it by casting:
`cast(address, Address)`

2024-03-05 16:43 UTC, organic1337 commented on 03_data_dawg/python_exercise/my_approvals.py
> +    main()
Mypy threw the following error:
```
my_approvals.py:42: error: No overload variant of "contract" of "Eth" matches argument types "str", "list[dict[str, Sequence[Collection[str]]]]"  [call-overload]
my_approvals.py:42: note: Possible overload variants:
my_approvals.py:42: note:     def contract(self, address: None = ..., **kwargs: Any) -> type[Contract]
my_approvals.py:42: note:     def contract(self, address: Address | ChecksumAddress | ENS, **kwargs: Any) -> Contract
my_approvals.py:49: error: List item 0 has incompatible type "str"; expected "Hash32 | HexBytes | HexStr | Sequence[Hash32 | HexBytes | HexStr] | None"  [list-item]
my_approvals.py:50: error: List item 1 has incompatible type "str"; expected "Hash32 | HexBytes | HexStr | Sequence[Hash32 | HexBytes | HexStr] | None"  [list-item]
Found 3 errors in 1 file (checked 1 source file)
```

that's because the web3 library type annotations has some bugs.
I've fixed it by casting:
`cast(address, Address)`

2024-03-05 16:43 UTC, organic1337 commented on 03_data_dawg/python_exercise/my_approvals.py
> +    def _get_transaction(self, eoa: Address) -> None:
Oops, removed

2024-03-05 16:53 UTC, organic1337 commented on 03_data_dawg/python_exercise/my_approvals.py
> +        contract = self.w3.eth.contract(address, abi=abi)
Declared it for better readability. here is how it is without it:
```python
self.w3.eth.contract(cast(Address, address), abi=NAMED_CONTRACT_ABI).functions.name().call()
```

4 me it too may function calls in one line. Don't you agree?

2024-03-06 11:35 UTC, danlaav1 approved these changes

2024-03-06 11:51 UTC, merged